# Generated by Django 4.1.7 on 2023-03-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=102)),
                ('town', models.CharField(max_length=1024)),
                ('postcode', models.CharField(max_length=1024)),
                ('card_no', models.IntegerField()),
                ('card_expiry_month', models.PositiveIntegerField()),
                ('card_expiry_year', models.PositiveIntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauce', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size')),
            ],
        ),
    ]
