# Generated by Django 4.1.5 on 2023-02-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_remove_customer_is_returned_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Customer',
        ),
    ]
