# Generated by Django 4.1.5 on 2023-02-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_returned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.book')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.customer'),
        ),
    ]
