# Generated by Django 4.1.5 on 2023-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_remove_book_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
