# Generated by Django 3.2.15 on 2023-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca298shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=50),
        ),
    ]
